default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

# 開発環境
development:
  <<: *default
  database: sample_app_development

# テスト環境
test:
  <<: *default
  database: sample_app_test

# 本番環境
production:
  <<: *default
  database: sample_app_production
  username: sample_app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>