default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: pguser
  password: pgpassword

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: sample_app_production
  username: sample_app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
